/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAiConsultationDurationRouteImport } from './routes/admin.ai-consultation-duration'
import { Route as AdminAiFollowupRouteImport } from './routes/admin.ai-followup'
import { Route as AdminAiQueueFlowRouteImport } from './routes/admin.ai-queue-flow'
import { Route as AdminAiSmartAssignmentRouteImport } from './routes/admin.ai-smart-assignment'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminQueueSettingsRouteImport } from './routes/admin.queue-settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'
import { Route as AdminSystemSettingsRouteImport } from './routes/admin.system-settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as DoctorHistoryRouteImport } from './routes/doctor.history'
import { Route as DoctorLoginRouteImport } from './routes/doctor.login'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorQueueRouteImport } from './routes/doctor.queue'
import { Route as QueueIndexRouteImport } from './routes/queue.index'
import { Route as QueueNewRouteImport } from './routes/queue.new'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffAppointmentsRouteImport } from './routes/staff.appointments'
import { Route as StaffDoctorAssignmentRouteImport } from './routes/staff.doctor-assignment'
import { Route as StaffEmergencyRouteImport } from './routes/staff.emergency'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as StaffNotificationsRouteImport } from './routes/staff.notifications'
import { Route as StaffProfileRouteImport } from './routes/staff.profile'
import { Route as StaffQueueMonitorRouteImport } from './routes/staff.queue-monitor'
import { Route as StaffReportsRouteImport } from './routes/staff.reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiConsultationDurationRoute =
  AdminAiConsultationDurationRouteImport.update({
    id: '/admin/ai-consultation-duration',
    path: '/admin/ai-consultation-duration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAiFollowupRoute = AdminAiFollowupRouteImport.update({
  id: '/admin/ai-followup',
  path: '/admin/ai-followup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiQueueFlowRoute = AdminAiQueueFlowRouteImport.update({
  id: '/admin/ai-queue-flow',
  path: '/admin/ai-queue-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiSmartAssignmentRoute = AdminAiSmartAssignmentRouteImport.update({
  id: '/admin/ai-smart-assignment',
  path: '/admin/ai-smart-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQueueSettingsRoute = AdminQueueSettingsRouteImport.update({
  id: '/admin/queue-settings',
  path: '/admin/queue-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/admin/schedules',
  path: '/admin/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemSettingsRoute = AdminSystemSettingsRouteImport.update({
  id: '/admin/system-settings',
  path: '/admin/system-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/doctor/appointments',
  path: '/doctor/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorHistoryRoute = DoctorHistoryRouteImport.update({
  id: '/doctor/history',
  path: '/doctor/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorLoginRoute = DoctorLoginRouteImport.update({
  id: '/doctor/login',
  path: '/doctor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/doctor/profile',
  path: '/doctor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorQueueRoute = DoctorQueueRouteImport.update({
  id: '/doctor/queue',
  path: '/doctor/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueNewRoute = QueueNewRouteImport.update({
  id: '/queue/new',
  path: '/queue/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAppointmentsRoute = StaffAppointmentsRouteImport.update({
  id: '/staff/appointments',
  path: '/staff/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDoctorAssignmentRoute = StaffDoctorAssignmentRouteImport.update({
  id: '/staff/doctor-assignment',
  path: '/staff/doctor-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffEmergencyRoute = StaffEmergencyRouteImport.update({
  id: '/staff/emergency',
  path: '/staff/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/staff/notifications',
  path: '/staff/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/staff/profile',
  path: '/staff/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffQueueMonitorRoute = StaffQueueMonitorRouteImport.update({
  id: '/staff/queue-monitor',
  path: '/staff/queue-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/staff/reports',
  path: '/staff/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/ai-consultation-duration': typeof AdminAiConsultationDurationRoute
  '/admin/ai-followup': typeof AdminAiFollowupRoute
  '/admin/ai-queue-flow': typeof AdminAiQueueFlowRoute
  '/admin/ai-smart-assignment': typeof AdminAiSmartAssignmentRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/queue-settings': typeof AdminQueueSettingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/system-settings': typeof AdminSystemSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/history': typeof DoctorHistoryRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/queue/new': typeof QueueNewRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/doctor-assignment': typeof StaffDoctorAssignmentRoute
  '/staff/emergency': typeof StaffEmergencyRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/queue-monitor': typeof StaffQueueMonitorRoute
  '/staff/reports': typeof StaffReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/ai-consultation-duration': typeof AdminAiConsultationDurationRoute
  '/admin/ai-followup': typeof AdminAiFollowupRoute
  '/admin/ai-queue-flow': typeof AdminAiQueueFlowRoute
  '/admin/ai-smart-assignment': typeof AdminAiSmartAssignmentRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/queue-settings': typeof AdminQueueSettingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/system-settings': typeof AdminSystemSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/history': typeof DoctorHistoryRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/queue/new': typeof QueueNewRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/doctor-assignment': typeof StaffDoctorAssignmentRoute
  '/staff/emergency': typeof StaffEmergencyRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/queue-monitor': typeof StaffQueueMonitorRoute
  '/staff/reports': typeof StaffReportsRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/queue': typeof QueueIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/ai-consultation-duration': typeof AdminAiConsultationDurationRoute
  '/admin/ai-followup': typeof AdminAiFollowupRoute
  '/admin/ai-queue-flow': typeof AdminAiQueueFlowRoute
  '/admin/ai-smart-assignment': typeof AdminAiSmartAssignmentRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/queue-settings': typeof AdminQueueSettingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/system-settings': typeof AdminSystemSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/history': typeof DoctorHistoryRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/queue/new': typeof QueueNewRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/doctor-assignment': typeof StaffDoctorAssignmentRoute
  '/staff/emergency': typeof StaffEmergencyRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/queue-monitor': typeof StaffQueueMonitorRoute
  '/staff/reports': typeof StaffReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/dashboard'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/admin/ai-consultation-duration'
    | '/admin/ai-followup'
    | '/admin/ai-queue-flow'
    | '/admin/ai-smart-assignment'
    | '/admin/audit-logs'
    | '/admin/departments'
    | '/admin/doctors'
    | '/admin/login'
    | '/admin/queue-settings'
    | '/admin/reports'
    | '/admin/schedules'
    | '/admin/system-settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/history'
    | '/doctor/login'
    | '/doctor/profile'
    | '/doctor/queue'
    | '/queue/new'
    | '/staff/appointments'
    | '/staff/doctor-assignment'
    | '/staff/emergency'
    | '/staff/login'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/queue-monitor'
    | '/staff/reports'
    | '/admin/'
    | '/doctor/'
    | '/queue/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/dashboard'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/admin/ai-consultation-duration'
    | '/admin/ai-followup'
    | '/admin/ai-queue-flow'
    | '/admin/ai-smart-assignment'
    | '/admin/audit-logs'
    | '/admin/departments'
    | '/admin/doctors'
    | '/admin/login'
    | '/admin/queue-settings'
    | '/admin/reports'
    | '/admin/schedules'
    | '/admin/system-settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/history'
    | '/doctor/login'
    | '/doctor/profile'
    | '/doctor/queue'
    | '/queue/new'
    | '/staff/appointments'
    | '/staff/doctor-assignment'
    | '/staff/emergency'
    | '/staff/login'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/queue-monitor'
    | '/staff/reports'
    | '/admin'
    | '/doctor'
    | '/queue'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/dashboard'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/admin/ai-consultation-duration'
    | '/admin/ai-followup'
    | '/admin/ai-queue-flow'
    | '/admin/ai-smart-assignment'
    | '/admin/audit-logs'
    | '/admin/departments'
    | '/admin/doctors'
    | '/admin/login'
    | '/admin/queue-settings'
    | '/admin/reports'
    | '/admin/schedules'
    | '/admin/system-settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/history'
    | '/doctor/login'
    | '/doctor/profile'
    | '/doctor/queue'
    | '/queue/new'
    | '/staff/appointments'
    | '/staff/doctor-assignment'
    | '/staff/emergency'
    | '/staff/login'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/queue-monitor'
    | '/staff/reports'
    | '/admin/'
    | '/doctor/'
    | '/queue/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AdminAiConsultationDurationRoute: typeof AdminAiConsultationDurationRoute
  AdminAiFollowupRoute: typeof AdminAiFollowupRoute
  AdminAiQueueFlowRoute: typeof AdminAiQueueFlowRoute
  AdminAiSmartAssignmentRoute: typeof AdminAiSmartAssignmentRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminQueueSettingsRoute: typeof AdminQueueSettingsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminSystemSettingsRoute: typeof AdminSystemSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorHistoryRoute: typeof DoctorHistoryRoute
  DoctorLoginRoute: typeof DoctorLoginRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorQueueRoute: typeof DoctorQueueRoute
  QueueNewRoute: typeof QueueNewRoute
  StaffAppointmentsRoute: typeof StaffAppointmentsRoute
  StaffDoctorAssignmentRoute: typeof StaffDoctorAssignmentRoute
  StaffEmergencyRoute: typeof StaffEmergencyRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StaffQueueMonitorRoute: typeof StaffQueueMonitorRoute
  StaffReportsRoute: typeof StaffReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-consultation-duration': {
      id: '/admin/ai-consultation-duration'
      path: '/admin/ai-consultation-duration'
      fullPath: '/admin/ai-consultation-duration'
      preLoaderRoute: typeof AdminAiConsultationDurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-followup': {
      id: '/admin/ai-followup'
      path: '/admin/ai-followup'
      fullPath: '/admin/ai-followup'
      preLoaderRoute: typeof AdminAiFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-queue-flow': {
      id: '/admin/ai-queue-flow'
      path: '/admin/ai-queue-flow'
      fullPath: '/admin/ai-queue-flow'
      preLoaderRoute: typeof AdminAiQueueFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-smart-assignment': {
      id: '/admin/ai-smart-assignment'
      path: '/admin/ai-smart-assignment'
      fullPath: '/admin/ai-smart-assignment'
      preLoaderRoute: typeof AdminAiSmartAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/queue-settings': {
      id: '/admin/queue-settings'
      path: '/admin/queue-settings'
      fullPath: '/admin/queue-settings'
      preLoaderRoute: typeof AdminQueueSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/admin/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system-settings': {
      id: '/admin/system-settings'
      path: '/admin/system-settings'
      fullPath: '/admin/system-settings'
      preLoaderRoute: typeof AdminSystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/history': {
      id: '/doctor/history'
      path: '/doctor/history'
      fullPath: '/doctor/history'
      preLoaderRoute: typeof DoctorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/login': {
      id: '/doctor/login'
      path: '/doctor/login'
      fullPath: '/doctor/login'
      preLoaderRoute: typeof DoctorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/queue': {
      id: '/doctor/queue'
      path: '/doctor/queue'
      fullPath: '/doctor/queue'
      preLoaderRoute: typeof DoctorQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/new': {
      id: '/queue/new'
      path: '/queue/new'
      fullPath: '/queue/new'
      preLoaderRoute: typeof QueueNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/appointments': {
      id: '/staff/appointments'
      path: '/staff/appointments'
      fullPath: '/staff/appointments'
      preLoaderRoute: typeof StaffAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/doctor-assignment': {
      id: '/staff/doctor-assignment'
      path: '/staff/doctor-assignment'
      fullPath: '/staff/doctor-assignment'
      preLoaderRoute: typeof StaffDoctorAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/emergency': {
      id: '/staff/emergency'
      path: '/staff/emergency'
      fullPath: '/staff/emergency'
      preLoaderRoute: typeof StaffEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/staff/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/staff/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/queue-monitor': {
      id: '/staff/queue-monitor'
      path: '/staff/queue-monitor'
      fullPath: '/staff/queue-monitor'
      preLoaderRoute: typeof StaffQueueMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/staff/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AdminAiConsultationDurationRoute: AdminAiConsultationDurationRoute,
  AdminAiFollowupRoute: AdminAiFollowupRoute,
  AdminAiQueueFlowRoute: AdminAiQueueFlowRoute,
  AdminAiSmartAssignmentRoute: AdminAiSmartAssignmentRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminQueueSettingsRoute: AdminQueueSettingsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminSystemSettingsRoute: AdminSystemSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorHistoryRoute: DoctorHistoryRoute,
  DoctorLoginRoute: DoctorLoginRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorQueueRoute: DoctorQueueRoute,
  QueueNewRoute: QueueNewRoute,
  StaffAppointmentsRoute: StaffAppointmentsRoute,
  StaffDoctorAssignmentRoute: StaffDoctorAssignmentRoute,
  StaffEmergencyRoute: StaffEmergencyRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffProfileRoute: StaffProfileRoute,
  StaffQueueMonitorRoute: StaffQueueMonitorRoute,
  StaffReportsRoute: StaffReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
